// Code generated by kessoku. DO NOT EDIT.

package seeders

import (
	"context"
	"github.com/mazrean/kessoku"
	"ndinhbang/go-template/pkg/config"
	"ndinhbang/go-template/pkg/db"
)

func Initialize(ctx context.Context) (*Seeder, error) {
	var err error
	config0, err := kessoku.Provide(config.LoadFromEnv).Fn()()
	if err != nil {
		var zero *Seeder
		return zero, err
	}
	databaseConfig := kessoku.Provide(config.GetDatabaseConfig).Fn()(config0)
	var err0 error
	postgresDatabase, err0 := kessoku.Async(kessoku.Provide(db.NewPostgresDatabase)).Fn()(ctx, databaseConfig)
	if err0 != nil {
		var zero *Seeder
		return zero, err0
	}
	seeder := kessoku.Provide(NewSeeder).Fn()(databaseConfig, postgresDatabase)
	return seeder, nil
}
