// Code generated by kessoku. DO NOT EDIT.

package app

import (
	"context"
	"github.com/mazrean/kessoku"
	"ndinhbang/go-template/internal/delivery/http/middleware"
	"ndinhbang/go-template/internal/delivery/http/routes"
	"ndinhbang/go-template/internal/delivery/http/v1"
	"ndinhbang/go-template/internal/delivery/http/v1/handlers"
	"ndinhbang/go-template/internal/delivery/http/v2"
	"ndinhbang/go-template/internal/repository/postgres"
	"ndinhbang/go-template/internal/usecase/role"
	"ndinhbang/go-template/internal/usecase/user"
	"ndinhbang/go-template/pkg/authorizer"
	"ndinhbang/go-template/pkg/config"
	"ndinhbang/go-template/pkg/db"
	"ndinhbang/go-template/pkg/server"
)

func Initialize(ctx context.Context) (*App, error) {
	var err error
	config0, err := kessoku.Provide(config.LoadFromEnv).Fn()()
	if err != nil {
		var zero *App
		return zero, err
	}
	serverConfig := kessoku.Provide(config.GetServerConfig).Fn()(config0)
	databaseConfig := kessoku.Provide(config.GetDatabaseConfig).Fn()(config0)
	server0 := kessoku.Provide(server.New).Fn()(serverConfig)
	var err0 error
	postgresDatabase, err0 := kessoku.Async(kessoku.Provide(db.NewPostgresDatabase)).Fn()(ctx, databaseConfig)
	if err0 != nil {
		var zero *App
		return zero, err0
	}
	var err1 error
	authorizer0, err1 := kessoku.Provide(authorizer.NewDefaultAuthorizer).Fn()(postgresDatabase, databaseConfig)
	if err1 != nil {
		var zero *App
		return zero, err1
	}
	authMiddleware := kessoku.Provide(middleware.NewAuthMiddleware).Fn()(postgresDatabase)
	userRepository := kessoku.Bind[user.Repository](kessoku.Provide(postgres.NewUserRepository)).Fn()(postgresDatabase)
	roleRepository := kessoku.Bind[role.Repository](kessoku.Provide(postgres.NewRoleRepository)).Fn()(postgresDatabase)
	casbinMiddleware := kessoku.Provide(middleware.NewCasbinMiddleware).Fn()(authorizer0)
	authorizeHandler := kessoku.Provide(handlers.NewAuthorizeHandler).Fn()(authorizer0, postgresDatabase)
	service := kessoku.Provide(user.NewService).Fn()(userRepository)
	service0 := kessoku.Provide(role.NewService).Fn()(roleRepository)
	userHandler := kessoku.Provide(handlers.NewUserHandler).Fn()(service)
	roleHandler := kessoku.Provide(handlers.NewRoleHandler).Fn()(service0)
	routeRegistrar := kessoku.Provide(v1.New).Fn()(userHandler, roleHandler)
	routeRegistrar0 := kessoku.Provide(v2.New).Fn()(userHandler, roleHandler)
	registrar := kessoku.Bind[server.RouteRegistrar](kessoku.Provide(routes.NewRegistrar)).Fn()(routeRegistrar, routeRegistrar0, authMiddleware, casbinMiddleware, authorizeHandler)
	app := kessoku.Provide(NewApp).Fn()(config0, server0, postgresDatabase, authorizer0, registrar)
	return app, nil
}
