// Code generated by kessoku. DO NOT EDIT.

package app

import (
	"context"
	"github.com/mazrean/kessoku"
	"ndinhbang/go-template/pkg/authorizer"
	"ndinhbang/go-template/pkg/config"
	"ndinhbang/go-template/pkg/db"
	"ndinhbang/go-template/pkg/server"
)

func Initialize(ctx context.Context) (*App, error) {
	var err error
	config0, err := kessoku.Provide(config.LoadFromEnv).Fn()()
	if err != nil {
		var zero *App
		return zero, err
	}
	serverConfig := kessoku.Provide(config.GetServerConfig).Fn()(config0)
	databaseConfig := kessoku.Provide(config.GetDatabaseConfig).Fn()(config0)
	server0 := kessoku.Provide(server.New).Fn()(serverConfig)
	var err0 error
	postgresDatabase, err0 := kessoku.Async(kessoku.Provide(db.NewPostgresDatabase)).Fn()(ctx, databaseConfig)
	if err0 != nil {
		var zero *App
		return zero, err0
	}
	var err1 error
	authorizer0, err1 := kessoku.Provide(authorizer.NewDefaultAuthorizer).Fn()(postgresDatabase, databaseConfig)
	if err1 != nil {
		var zero *App
		return zero, err1
	}
	app := kessoku.Provide(NewApp).Fn()(config0, server0, postgresDatabase, authorizer0)
	return app, nil
}
